services:

  usm_asterisk:
    build:
      context: ${USERSIDE_BASE_DIR}/usm_asterisk
    restart: always
    environment:
      USERSIDE_API_KEY: 'userside-api-key'
      ASTERISK_HOST: 'asterisk.server.address'
      ASTERISK_PORT: 5038
      ASTERISK_USERNAME: 'admin'
      ASTERISK_SECRET: 'passwd1234'
      ASTERISK_PROTOCOL_VERSION: 3
      ASTERISK_FROM_CONTEXTS: 'from-trunk'  # incomeing contexts separated by a space
    volumes:
      - ${USERSIDE_BASE_DIR}/usm_asterisk/module:/app
      - ${USERSIDE_BASE_DIR}/usm_asterisk/log:/var/log
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - internal